name: random_picture
description: Random picture generator with custom colors and patterns.
version: 0.0.1-alpha
homepage: https://github.com/ChemisTechlabs/random_picture
author: Guilherme Caldas <gcaldas@chemis.org>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  image: ^2.1.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
